---
title: "qpcr 18.09.10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(cowplot)

```

```{r, get data}
cts <- read.table("file:///C:/Users/rgoer/Documents/qPCR stuff/18.05.09 rg qPCR.csv", header = TRUE, sep = ",")

```

```{r, organize}
cts_tidy <- cts %>% 
  as_tibble() 
cts_tidy <- cts_tidy %>% 
  separate(Well, into = c("row", "col"), sep = 1) %>%
  mutate(gene = ifelse(row == "A" | 
                       row == "B" | 
                       row == "C", "FMR1", 
                       ifelse(row == "D" |
                              row == "E" |
                              row == "F" , "HPRT", "empty"))) %>% 
  filter(gene != "empty") %>%
  mutate(RT = ifelse(col == "01" | 
                     col == "03" | 
                     col == "05" |
                     col == "07" |
                     col == "09" |
                     col == "11" | 
                     col == "13" |
                     col == "15" |
                     col == "17" |
                     col == "19", "pRT", 
                     ifelse(col == "02" |
                            col == "04" |
                            col == "06" |
                            col == "08" |
                            col == "10" |
                            col == "12" |
                            col == "14" |
                            col == "16" |
                            col == "18" |
                            col == "20", "mRT", "empty"))) %>% 
  filter(RT != "empty") %>% 
  mutate(clone = ifelse(col == "01" | col == "02", "c1-27",
                 ifelse(col == "03" | col == "04", "c1-32",
                 ifelse(col == "05" | col == "06", "c1-41",
                 ifelse(col == "07" | col == "08", "c1-65",
                 ifelse(col == "09" | col == "10", "c2-33",
                 ifelse(col == "11" | col == "12", "c2-51",
                 ifelse(col == "13" | col == "14", "c2-57",
                 ifelse(col == "15" | col == "16", "c2-70",
                 ifelse(col == "17" | col == "18", "Pool",
                 ifelse(col == "19" | col == "20", "Lox", "empty"))))))))))) %>% 
  filter(clone != "empty") %>% 
  group_by(gene, RT, clone) %>% 
  mutate(Cq = ifelse(is.na(Cq), 40, Cq)) 
 
```

```{r, }
cts_mean <- cts_tidy %>%
  group_by(clone, gene, RT) %>% 
summarize(meanCq = mean(Cq), varCq = var(Cq))
exp <-  cts_mean %>%
  select(-varCq) %>% 
  spread(gene, meanCq) %>% 
  left_join(cts_tidy, .) %>% 
  mutate(dCT = Cq - HPRT, logdCT = 2^(-dCT)) %>% 
  group_by(gene, RT, clone) %>% 
  filter(RT == "pRT") %>%
  summarize(meanlogCT = mean(logdCT)) %>%
  mutate(normlogCT = meanlogCT / 1.00, 
         percent_KO = (1-normlogCT)*100)

```

```{r, }
cts_tidy %>% ggplot(aes(clone, -Cq, fill = RT)) + geom_boxplot() + geom_point(position = "jitter") + facet_grid(. ~gene)

exp %>% ggplot(aes(clone, normlogCT, fill = gene)) + geom_bar(stat = "identity", position = "dodge") 

exp %>% filter(gene == "FMR1") %>% mutate(percent_KO = normlogCT / 1.63) %>% ggplot(aes(clone, percent_KO, fill = clone)) + geom_bar(stat = "identity") + labs(y = "percent FMR1 Expression (%)", title = "FMR1 KO")

cts_mean %>%
  select(-varCq) %>% 
  spread(gene, meanCq) %>% 
  left_join(cts_tidy, .) %>% 
  mutate(dCT = Cq - HPRT, logdCT = 2^(-dCT)) %>% 
  group_by(gene, RT, clone) %>% 
  filter(RT == "pRT", gene == "FMR1") %>% 
    mutate(norm_KO = (logdCT / 0.767)*100) %>% ggplot(aes(clone, norm_KO, col = clone)) + geom_point(position = position_jitter(width = 0.1, height = 0.1)) + geom_boxplot() + guides(col = FALSE) + scale_y_continuous(limits = c(10, 100)) + labs(y = "Percent FMR1 expression (%)", title = "FMR1 qPCR of Sorted Clones")

```


