---
title: "CAD RP constructs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cowplot)
library(ggpubr)
```

Luc:
FF = HEX
RE = FAM

Chk:
Ranbp1 = FAM
Tsc1 = HEX

```{r, get qPCR data}
cts <- as_tibble(read.table("admin_2021-04-30 17-49-36_796BR02132 -  Quantification Cq Results.csv", header = TRUE, sep = ",")) %>% mutate(plate = 1)
cts2 <- as_tibble(read.csv("admin_2021-05-15 18-46-41_796BR02132 -  Quantification Cq Results.csv", header = TRUE)) %>% mutate(plate = 2)
```

```{r, }
cts_tidy <- bind_rows(cts,cts2)  %>% 
  separate(Well, into = c("row", "col"), sep = 1) %>%
  mutate(cell = ifelse(row %in% c("A", "B", "C") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 1, "RPL8",
                      ifelse(row %in% c("D", "E", "F") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 1, "FF",
                      ifelse(row %in% c("G", "H", "I") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 1, "WT",
                      ifelse(row %in% c("J", "K", "L") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 1, "mut",
                      ifelse(row %in% c("A", "B", "C") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 2, "RPL7",
                      ifelse(row %in% c("D", "E", "F") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 2, "RPL7mut",
                      ifelse(row %in% c("G", "H", "I") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 2, "RPS28",
                      ifelse(row %in% c("J", "K", "L") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 2, "RPS28mut",
                      ifelse(row %in% c("M", "N", "O") & col %in% c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12") & plate == 2, "FF",
                      ifelse(row %in% c("A", "B", "C") & col %in% as.character(c(13:16, 19:22)) & plate == 2, "WT",
                      ifelse(row %in% c("A", "B", "C") & col %in% as.character(c(17, 18, 23, 24)) & plate == 2, "mut", "empty")))))))))))) %>% 
  filter(cell != "empty") %>%
  mutate(gene = ifelse(col %in% c("01", "03", "05", "07", "09", "11", "13", "15", "17", "19", "21", "23"), "Luc",
                ifelse(col %in% c("02", "04", "06", "08", "10", "12", "14", "16", "18", "20", "22", "24"), "Chk", "empty"))) %>% 
  filter(gene != "empty") %>% 
  mutate(biorep = ifelse(col %in% c("01", "02", "07", "08") & plate == 1, "rep1", 
                  ifelse(col %in% c("03", "04", "09", "10") & plate == 1, "rep2",
                  ifelse(col %in% c("05", "06", "11", "12") & plate == 1, "rep3",
                  ifelse(cell %in% c("RPL7", "RPL7mut", "RPS28", "RPS28mut") & col %in% c("01", "02", "07", "08") & plate == 2, "rep1",
                  ifelse(cell %in% c("RPL7", "RPL7mut", "RPS28", "RPS28mut") & col %in% c("03", "04", "09", "10") & plate == 2, "rep2",
                  ifelse(cell %in% c("RPL7", "RPL7mut", "RPS28", "RPS28mut") & col %in% c("05", "06", "11", "12") & plate == 2, "rep3",
                  ifelse(cell == "FF" & col %in% c("01", "02", "07", "08") & plate == 2, "rep4",
                  ifelse(cell == "FF" & col %in% c("03", "04", "09", "10") & plate == 2, "rep5",
                  ifelse(cell == "FF" & col %in% c("05", "06", "11", "12") & plate == 2, "rep6",
                  ifelse(cell == "WT" & col %in% c("13", "14", "19", "20") & plate == 2, "rep4",
                  ifelse(cell == "WT" & col %in% c("15", "16", "21", "22") & plate == 2, "rep5",
                  ifelse(cell == "mut" & col %in% c("17", "18", "23", "24") & plate == 2, "rep4", "empty"))))))))))))) %>% 
  filter(biorep != "empty") %>% 
  mutate(fraction = ifelse(col %in% c("01", "02", "03", "04", "05", "06", "13", "14", "15", "16", "17" , "18"), "soma",
                    ifelse(col %in% c("07", "08", "09", "10", "11", "12", "19", "20", "21", "22", "23", "24"), "neurite", "empty"))) %>% 
  filter(fraction != "empty") %>% 
  filter(Fluor == "FAM" | Fluor == "HEX") %>% 
  select(plate, row, col, Fluor, cell, gene, biorep, fraction, Cq) %>% 
  mutate(#Cq = ifelse(is.na(Cq), 40, Cq),
         rep = rep(c(1,2,3), nrow(.)/3)) 

```
  
```{r, }
cts_tidy %>% ggplot(aes(x = cell, y = -Cq, col = fraction)) + geom_point(position = "jitter") + facet_grid(Fluor~gene) + theme_cowplot()

cts_tidy %>% spread(Fluor, Cq) %>% rowwise() %>% mutate(LR = ifelse(gene == "Chk", 2^(-(FAM - HEX)), ifelse(gene == "Luc", 2^(-(HEX-FAM)), NA))) %>% ggplot(aes(x = cell, y = LR, fill = fraction)) + geom_boxplot(outlier.shape = NA) + geom_point(aes(shape = biorep,col = fraction), position = position_jitterdodge()) + facet_wrap(.~gene, scales = "free") + theme_cowplot() + guides(fill = FALSE, col = FALSE)

cts_tidy %>% spread(Fluor, Cq) %>% rowwise() %>% mutate(LR = ifelse(gene == "Chk", 2^(-(FAM - HEX)), ifelse(gene == "Luc", 2^(-(HEX-FAM)), NA))) %>% group_by(cell,gene,biorep,fraction) %>% summarise(mean_LR = mean(LR, na.rm = TRUE)) %>% spread(fraction,mean_LR) %>% ggplot(aes(x = cell, y = neurite/soma, col = cell)) + geom_boxplot(outlier.shape = NA) + geom_point(aes(shape = biorep), position = position_jitterdodge()) + facet_wrap(.~gene, scales = "free") + theme_cowplot() + guides(fill = FALSE, col = FALSE)

```

```{r, }
cts_mean <- cts_tidy %>% 
    spread(Fluor, Cq) %>%
    mutate(LR = ifelse(gene == "Chk", 2^(-(FAM - HEX)), 
                ifelse(gene == "Luc", 2^(-(HEX-FAM)), NA))) %>% 
    group_by(cell,gene,biorep,fraction) %>% 
    summarize(meanLR = mean(LR, na.rm = TRUE)) 

cts_mean <- cts_mean %>% 
  mutate(keep = ifelse(cell == "FF" & biorep %in% c("rep1", "rep2", "rep3"), "no",
                ifelse(cell == "mut" & biorep %in% c("rep3", "rep4"), "no",
                ifelse(cell == "WT" & biorep %in% c("rep2","rep3"), "no", "yes")))) %>% 
  filter(keep == "yes")

cts_mean %>% ggplot(aes(x = cell, y = meanLR, col = fraction, shape = biorep)) + geom_point() + theme_cowplot() + facet_wrap(.~gene, scales = "free")

cts_mean %>% 
  spread(fraction, meanLR) %>%
  mutate(LR = neurite/soma) %>% 
  ggplot(aes(x = cell, y = LR, col = cell, shape = biorep)) + 
  geom_point(position = "jitter", size = 4) + 
  facet_grid(.~gene) + 
  theme_cowplot() + 
  guides(col = FALSE) + 
  labs(x = "") +
  stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut"), c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPS28", "RPS28mut"), c("FF", "RPL8"), c("FF", "WT"), c("FF", "mut"), c("WT", "mut")), method = "t.test")

cts_mean %>% 
    mutate(meanLR = log2(meanLR)) %>% 
    spread(fraction, meanLR) %>%
    mutate(LR = neurite - soma) %>% 
    ggplot(aes(x = cell, y = 2^-LR, col = cell, shape = biorep)) + 
    geom_point(position = "jitter", size = 4) + 
    facet_wrap(.~gene, scales = "free") + 
    theme_cowplot() + 
    guides(col = FALSE) + 
    labs(x = "") +
  stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut"), c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPS28", "RPS28mut"), c("FF", "RPL8"), c("FF", "WT"), c("FF", "mut"), c("WT", "mut")), method = "t.test")

```

```{r, plate view}
cts_tidy %>% 
  filter(Fluor == "HEX") %>% 
  ggplot(aes(col, row)) +
  geom_tile(aes(fill = Cq)) + 
  geom_text(aes(label = round(Cq, 1))) +
  scale_fill_gradient(low = "red", high = "white") +
  scale_y_discrete(limits=rev) + 
  facet_grid(.~plate)
```

```{r, }
cts_mean %>% 
  spread(fraction,meanLR) %>% 
  mutate(ns = neurite/soma) %>%
  ungroup() %>%  
  select(-neurite,-soma) %>% 
  na.omit() %>% 
  spread(gene,ns) %>% 
  mutate(norm_LR = Luc/Chk) %>% 
  ggplot(aes(x = cell, y = norm_LR, col = cell)) + 
  theme_cowplot() + 
  geom_point(aes(shape = biorep)) +
  stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut"), c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPS28", "RPS28mut"), c("FF", "RPL8"), c("FF", "WT"), c("FF", "mut"), c("WT", "mut")), method = "t.test")

```

```{r, }
cts_tidy %>% 
    spread(Fluor, Cq) %>% 
  mutate(keep = ifelse(cell == "FF" & biorep %in% c("rep1", "rep2", "rep3"), "no",
                ifelse(cell == "mut" & biorep %in% c("rep3", "rep4"), "no",
                ifelse(cell == "WT" & biorep %in% c("rep2","rep3"), "no", "yes")))) %>% 
  filter(keep == "yes") %>% 
    mutate(`FF/RE` = 2^(-(FAM - HEX))) %>% 
    select(-FAM,-HEX) %>% 
    filter(gene == "Luc") %>% group_by(cell,biorep,fraction) %>% summarize(`meanFF/RE` = mean(`FF/RE`, na.rm = TRUE)) %>% spread(fraction,`meanFF/RE`) %>% mutate(LR = neurite/soma) %>% ggplot(aes(x = cell, y = LR, col = cell, shape = biorep)) + geom_point(position = "jitter") + theme_cowplot() +
    stat_compare_means(comparisons = list(c("FF", "RPL7"), c("FF", "RPL7mut"), c("RPL7", "RPL7mut"), c("FF", "RPS28"), c("FF", "RPS28mut"), c("RPS28", "RPS28mut"), c("FF", "RPL8"), c("FF", "WT"), c("FF", "mut"), c("WT", "mut")), method = "t.test")
```

```{r, AAdat}
AA <- read.csv("AA_Cqs.csv", header = TRUE)

AA %>% as_tibble() %>% gather(X1,X2,X3, key = "rep", value = "Cq") %>% spread(Fluor,Cq) %>% mutate(`FF/RE` = 2^(-(HEX-FAM))) %>% select(-FAM,-HEX) %>% group_by(cell,biorep,fraction) %>% summarise(`FF/RE` = mean(`FF/RE`, na.rm = TRUE)) %>% spread(fraction,`FF/RE`) %>% ggplot(aes(x = cell, y = Neurite/Soma, col = cell)) + geom_point(position = "jitter") + theme_cowplot()
```






  